// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sim
NumericVector sim(NumericMatrix out, float X0, float mu, float Dt, float sqrdt, float sigma);
RcppExport SEXP _rnmethods_sim(SEXP outSEXP, SEXP X0SEXP, SEXP muSEXP, SEXP DtSEXP, SEXP sqrdtSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type out(outSEXP);
    Rcpp::traits::input_parameter< float >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< float >::type mu(muSEXP);
    Rcpp::traits::input_parameter< float >::type Dt(DtSEXP);
    Rcpp::traits::input_parameter< float >::type sqrdt(sqrdtSEXP);
    Rcpp::traits::input_parameter< float >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(sim(out, X0, mu, Dt, sqrdt, sigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rnmethods_sim", (DL_FUNC) &_rnmethods_sim, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_rnmethods(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
