# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sim <- function(out, X0, mu, Dt, sqrdt, sigma) {
    .Call('_rnmethods_sim', PACKAGE = 'rnmethods', out, X0, mu, Dt, sqrdt, sigma)
}

